In [1]:
import pandas as pd

In [2]:
mobot = pd.read_csv("/Users/prince/philly-tree-mapper/notebooks/mobot_plant_data.csv")

In [3]:
mobot.loc[mobot["Scientific Name"] == "gleditsia triacanthos inermis"]

,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL
17,gleditsia triacanthos inermis,N/a,N/a,N/a,N/a,no results container,NaN
252,gleditsia triacanthos inermis,May to June,Greenish yellow to greenish white,Insignificant,Good Fall,manual search,https://www.missouribotanicalgarden.org/PlantF...

In [4]:
mobot.drop(32, inplace=True)
mobot.drop(17, inplace=True)

In [5]:
mobot

,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL
0,ginkgo biloba,April,Green,Insignificant,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
1,acer palmatum,April,Reddish-purple,Insignificant,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
2,acer pseudoplatanus,May,Yellow green,Insignificant,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
3,ilex opaca,May,Creamy white,Insignificant,Evergreen,matched,https://www.missouribotanicalgarden.org/PlantF...
4,koelreuteria paniculata,June to July,Yellow,Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
...,...,...,...,...,...,...,...
248,acer henryii,N/a,N/a,N/a,N/a,no results container,NaN
249,ulmus alata,March to April,Reddish green,Insignificant,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
250,prunus amanogawa,N/a,N/a,N/a,N/a,no results container,NaN
251,platanus acerifolia,April,Yellow (male) and red (female),Insignificant,N/a,manual search,https://www.missouribotanicalgarden.org/PlantF...
252,gleditsia triacanthos inermis,May to June,Greenish yellow to greenish white,Insignificant,Good Fall,manual search,https://www.missouribotanicalgarden.org/PlantF...

In [6]:
mobot.to_csv("/Users/prince/philly-tree-mapper/notebooks/mobot_plant_data.csv", index=False)